export interface Personal {
  id:any,
  nombre: string,
  paterno: string,
  materno: string,
  nroDNI: string,
  estadoCivil: string,
  fechaNacimiento: string
}
export interface PersonalList {
  id:number,
  nombre: string,
  nombre2?: string,
  paterno: string,
  materno: string,
  nroDNI: string,
  vigenciaDNI: string,
  nroRUC?: string,
  nroPasaporte?: string,
  vigenciaPasaporte?: string,
  estadoCivil: string,
  sexo: string,
  fechaNacimiento: string,
  celular?: string,
  celularTrab?: string,
  fijo?: string,
  telefonoRef?: string,
  fijoTrab?: string,
  anexo?: string,
  email?: string,
  emailTrab?: string,
  web?: string,
  nroLicencia?: string,
  vigenciaLicencia?: string,
  catLicencia?: string,
  codSalud?: string,
  fondoPension?: string,
  tipoAfp?: string,
  cuspp?: string,
  profesion?: string,
  peso?: string,
  talla?: string,
  contextura?: string,
  gruposangre?: string,
  foto?:string
}