export interface Personal {
  idpersona:any,
  nombre: string,
  paterno: string,
  materno: string,
  nrodni: string,
  estadocivil: string,
  fechanacimiento: string
}
export interface PersonalList {
  idpersona:any,
  nombre: string,
  nombre2?: string,
  paterno: string,
  materno: string,
  nrodni: string,
  vigenciadni: string,
  nroruc?: string,
  nropasaporte?: string,
  vigenciapasaporte?: string,
  idestadocivil?: any,
  estadocivil: string,
  idsexo?: any,
  sexo: string,
  fechanacimiento: string,
  celular?: string,
  celulartrab?: string,
  fijo?: string,
  telefonoref?: string,
  fijotrab?: string,
  anexo?: string,
  email?: string,
  emailtrab?: string,
  web?: string,
  nrolicencia?: string,
  vigencialicencia?: string,
  catLicencia?: string,
  codsalud?: string,
  idfondopension?:any,
  fondopension?: string,
  idtipoafp?: any,
  tipoafp?: string,
  cuspp?: string,
  profesion?: string,
  peso?: string,
  talla?: string,
  idcontextura?: any,
  contextura?: string,
  idgruposangre?: any,
  gruposangre?: string,
  foto?:string
  estado?: string,
  fechahora?: string,
  idusuario?:	any,
  usuario?:	any,
  idtran?: any
}