export interface Personal {
  nombre: string,
  paterno: string,
  materno: string,
  nroDNI: number,
  estadoCivil: string,
  fechaNacimiento: string
}
export interface PersonalList {
  id:number,
  nombre: string,
  nombre2?: string,
  paterno: string,
  materno: string,
  nroDNI: number,
  vigenciaDNI: string,
  nroRuc?: number,
  nroPasaporte?: number,
  vigenciaPasaporte?: string,
  estadoCivil: string,
  sexo: string,
  fechaNacimiento: string,
  celular?: number,
  celularTrab?: number,
  fijo?: number,
  telefonoRef?: number,
  fijoTrab?: number,
  anexo?: number,
  email?: string,
  emailTrab?: string,
  web?: string,
  nroLicencia?: number,
  vigenciaLicencia?: string,
  catLicencia?: string,
  codSalud?: number,
  fondoPension?: string,
  tipoAfp?: string,
  cuspp?: number,
  profesion?: string,
  peso?: string,
  talla?: string,
  contextura?: string,
  gruposangre?: string,
  foto?:string
}